language: ruby

sudo: false

cache: bundler

addons:
  apt:
    packages:
    - bsdtar

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.0
  - 2.5.1

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake test:unit
