FROM postgres:9.6-alpine

ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
    POSTGRES_DB=${POSTGRES_DB}

#RUN psql -U postgres -c "create user datadog with password '${POSTGRES_PASSWORD}';" && \
#    psql -U postgres -c "grant SELECT ON pg_stat_database to datadog;" && \
#    psql -U postgres -d ${POSTGRES_DB}  -c \
#         "select * from pg_stat_database LIMIT(1);" \
#         && echo -e "\e[0;32mPostgres connection - OK\e[0m" \
#         || echo -e "\e[0;31mCannot connect to Postgres\e[0m"
#    
