FROM nginx:mainline-alpine
LABEL maintainer "Yuya Ushijima <github:ushijimay>"

##Set environmental variables
ENV NGINX_HOST=${NGINX_HOST} \
    NGINX_PORT=${NGINX_PORT} \
    APP_HOST=${APP_HOST} \
    APP_PORT=${APP_PORT}

##Copy static files
RUN set -x && mkdir -p /usr/share/nginx/static
COPY app/testweb/static /usr/share/nginx/static

##Copy original nginx config template
COPY nginx/mysite.template /etc/nginx/conf.d/mysite.template

##Copy http stub status config template for Datadog 
COPY nginx/status.template /etc/nginx/conf.d/status.template

##Copy Nginx root conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

STOPSIGNAL SIGTERM

### Start Nginx
COPY nginx/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx"]
