from datadog import initialize, api

options = {
    'api_key': '2efb60934301e2e78970e9d6cf48c0cb',
    'app_key': 'f192e131e61400bca9ef338a03a8654b6c3146f7'
}

initialize(**options)

title = "Custom Metric data"
description = "Custom metrics generated by my_metrics with a 45 second interval"
graphs = [{
    "definition": {
        "events": [],
        "requests": [
            {"q": "avg:my_metric{*}"},
            {"q": "avg:my_metric{*}.rollup(sum, 3600)"}
        ],
        "viz": "timeseries"
    },
    "title": "random values between 0 and 1000"
}]

template_variables = [{
    "name": "timeboard",
    "prefix": "my_metric",
    "default": "host:datadogvm-ubuntu"
}]

read_only = True
api.Timeboard.create(title=title,
                     description=description,
                     graphs=graphs,
                     template_variables=template_variables,
                     read_only=read_only)