# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "serole" do |serole|
    serole.vm.hostname = "serole"
    serole.vm.provision :file, source: 'serole.sh', destination: 'serole.sh'
    serole.vm.provision :shell, privileged: false, path:  "serole.sh", args: "serole"
  end
end