version: "3"
services:
  db:
    image: library/mariadb:10-bionic
    container_name: mysql
    restart: always
    volumes:
      - /Users/bpabon/projects/datadog/mysql/var:/var/lib/mysql
      - /Users/bpabon/projects/datadog/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 127.0.0.1:3306:3306
      # - "3306:3306/tcp"
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE=my_db
    labels:
      com.datadoghq.ad.check_names: '[mysql]'
      com.datadoghq.ad.init_configs: ''
      com.datadoghq.ad.instances: '{"server": "%%host%%", "user": "%%env_$MYSQL_USER","pass": "%%env_$MYSQL_PASSWORD%%"}'
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    links:
      - db
    ports:
      - "8080:8080"
# agent section
  datadog:
      container_name: datadog
      build: datadog
      links:
        - db
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
        - /Users/bpabon/projects/datadog/hiring-engineers/zero2datadog/docker/datadog:/etc/datadog-agent
      environment:
        - DD_API_KEY=${DD_API_KEY}
        - DD_CONFIG_HOME=${DD_CONFIG_HOME}
        - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1
        - DD_APM_ENABLED=true  # Uncomment for APM tracing
