# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "terrellea"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 4999, host: 4999

  #config.vm.synced_folder "data", "/vagrant_data"

  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install python python-pip postgresql postgresql-contrib -q -y
  pip install -r /vagrant/app/requirements.txt
  nohup ddtrace-run python /vagrant/app/my_app.py >/dev/null 2>&1 &
   SHELL

end
