CREATE USER 'datadog' IDENTIFIED BY 'WIokxj0ir2+UVFOQR35qDbER';
GRANT REPLICATION CLIENT ON *.* TO 'datadog'; #WITH MAX_USER_CONNECTIONS 5;
GRANT PROCESS ON *.* TO 'datadog';
GRANT SELECT ON performance_schema.* TO 'datadog';