#!/bin/bash
set -e
mysql --protocol=socket -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL
CREATE USER '$DATADOG_MYSQL_USERNAME'@'%' IDENTIFIED BY '$DATADOG_MYSQL_PASSWORD';
GRANT REPLICATION CLIENT ON *.* TO '$DATADOG_MYSQL_USERNAME'@'%' WITH MAX_USER_CONNECTIONS 5;
GRANT PROCESS ON *.* TO '$DATADOG_MYSQL_USERNAME'@'%';
GRANT SELECT ON performance_schema.* TO '$DATADOG_MYSQL_USERNAME'@'%';
EOSQL
