version: '2'

services:
  # Postgres Container
  db:
    image: postgres
    restart: always
    networks:
      - docknet
    environment:
      POSTGRES_PASSWORD: datadog

              RUN apt-get update && apt-get install -y stress

    
  # Database Adminer Container    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    networks:
      - docknet
      
networks:
    docknet:
        external: true


ENTRYPOINT ["/usr/bin/stress", "--verbose"]
CMD []
