# -*- mode: ruby -*-
# vi: set ft=ruby :


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.define "datadog-project"
 config.vm.hostname = "datadog-project"
 config.vm.box = "bento/ubuntu-16.04"

 config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
 config.vm.network :forwarded_port, guest: 5050, host: 5050
  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
     vb.name = "datadog-project"
     vb.gui = false
     vb.memory = "1024"
   end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install postgresql postgresql-contrib -q -y
  SHELL

end
