FROM nginx:mainline-alpine

ARG MYNGINX_HOST
ARG MYNGINX_PORT
ARG MYAPP_HOST
ARG MYAPP_PORT

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    MYNGINX_HOST=$MYNGINX_HOST \
    MYNGINX_PORT=$MYNGINX_PORT \
    MYAPP_HOST=$MYAPP_HOST \
    MYAPP_PORT=$MYAPP_PORT

##Copy custom config templates
COPY nginx/mysite.template /etc/nginx/conf.d/mysite.template

##Copy Nginx root conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

STOPSIGNAL SIGTERM

### Start Nginx
COPY nginx/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx"]
