---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_user: root

  tasks:
    - name: add datadog.conf
      copy:
        src: conf/datadog.conf
        dest: /etc/dd-agent/datadog.conf
        owner: dd-agent
        group: dd-agent
        mode: 0644

    - name: restart agent
      service:
        name: datadog-agent
        state: restarted



