version: "3.4"

services:
    terraform:
        image: "hashicorp/terraform:light"
        env_file: .env
        volumes:
            - $PWD:/app
        working_dir: /app
        entrypoint: "sh"
        command: " -c '/bin/terraform init; /bin/terraform apply -auto-approve'"