version: '2'

services:
  # Postgres Container
  db:
    image: postgres
    restart: always
    networks:
      - docknet
    environment:
      POSTGRES_PASSWORD: datadog
    
  # Database Adminer Container    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    networks:
      - docknet 
      
networks:
    docknet:
        external: true